# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Glow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Glow
  pod 'SwiftGRPC'
  pod 'SwiftProtobuf', '~> 1.0'
  
  target 'GlowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GlowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
