# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc.proto',
  package='glow',
  syntax='proto3',
  serialized_options=_b('\n\020io.tamumake.glowB\004GlowP\001\242\002\003HLW'),
  serialized_pb=_b('\n\ngrpc.proto\x12\x04glow\"$\n\x0cPointRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1c\n\tGlowReply\x12\x0f\n\x07message\x18\x01 \x01(\t2C\n\x04Glow\x12;\n\x12TestPointReceiving\x12\x12.glow.PointRequest\x1a\x0f.glow.GlowReply\"\x00\x42 \n\x10io.tamumake.glowB\x04GlowP\x01\xa2\x02\x03HLWb\x06proto3')
)




_POINTREQUEST = _descriptor.Descriptor(
  name='PointRequest',
  full_name='glow.PointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='glow.PointRequest.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='glow.PointRequest.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=56,
)


_GLOWREPLY = _descriptor.Descriptor(
  name='GlowReply',
  full_name='glow.GlowReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='glow.GlowReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['PointRequest'] = _POINTREQUEST
DESCRIPTOR.message_types_by_name['GlowReply'] = _GLOWREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PointRequest = _reflection.GeneratedProtocolMessageType('PointRequest', (_message.Message,), dict(
  DESCRIPTOR = _POINTREQUEST,
  __module__ = 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:glow.PointRequest)
  ))
_sym_db.RegisterMessage(PointRequest)

GlowReply = _reflection.GeneratedProtocolMessageType('GlowReply', (_message.Message,), dict(
  DESCRIPTOR = _GLOWREPLY,
  __module__ = 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:glow.GlowReply)
  ))
_sym_db.RegisterMessage(GlowReply)


DESCRIPTOR._options = None

_GLOW = _descriptor.ServiceDescriptor(
  name='Glow',
  full_name='glow.Glow',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=155,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestPointReceiving',
    full_name='glow.Glow.TestPointReceiving',
    index=0,
    containing_service=None,
    input_type=_POINTREQUEST,
    output_type=_GLOWREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GLOW)

DESCRIPTOR.services_by_name['Glow'] = _GLOW

# @@protoc_insertion_point(module_scope)
